# Docker Compose Override Example
# Copy this file to docker-compose.override.yml to customize your local setup

version: '3.8'

services:
  # MySQL customizations
  mysql:
    environment:
      # Override default passwords (IMPORTANT: Change these!)
      MYSQL_ROOT_PASSWORD: your_custom_root_password_here
      MYSQL_PASSWORD: your_custom_app_password_here
    volumes:
      # Add custom MySQL configuration
      - ./config/mysql-custom.cnf:/etc/mysql/conf.d/custom-local.cnf:ro
    # Uncomment to expose MySQL on different port
    # ports:
    #   - "3307:3306"

  # SonarQube customizations
  sonarqube:
    environment:
      # Custom SonarQube database password
      SONAR_JDBC_PASSWORD: your_custom_sonar_password_here
    # Uncomment to expose SonarQube on different port
    # ports:
    #   - "9001:9000"
    volumes:
      # Add custom SonarQube configuration
      - ./config/sonar-custom.properties:/opt/sonarqube/conf/sonar.properties:ro

  # Development database with test data
  # mysql-dev:
  #   extends: mysql
  #   container_name: tcg_mysql_dev
  #   environment:
  #     MYSQL_DATABASE: tcg_shared_dev
  #   ports:
  #     - "3307:3306"
