name: SonarQube Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  sonarqube:
    name: SonarQube Code Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Shallow clones should be disabled for better analysis
          fetch-depth: 0

      - name: Set up Node.js (for future API analysis)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
        # Only run if package.json exists (Phase 2+)
        if: hashFiles('**/package.json') != ''

      - name: Install dependencies
        run: npm ci
        if: hashFiles('**/package.json') != ''

      - name: Run tests with coverage
        run: npm run test:coverage
        if: hashFiles('**/package.json') != ''

      - name: SonarQube Scan
        uses: sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: .
          args: >
            -Dproject.settings=config/sonar-project.properties

      - name: Quality Gate Check
        uses: sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
